spring:
  application:
    name: chassis-server
  datasource:
    url: jdbc:mysql://127.0.0.1:3316/amplication?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&createDatabaseIfNotExist=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123
    hikari:
      connection-timeout: 2000
      initialization-fail-timeout: 0
      auto-commit: false
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  jpa:
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      # modify batch size as necessary
      hibernate.jdbc.batch_size: 25
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.query.fail_on_pagination_over_collection_fetch: true
      hibernate.query.in_clause_parameter_padding: true
      hibernate.show_sql: true
      hibernate.format_sql: true
      hibernate.use_sql_comments: false
    hibernate:
      ddl-auto: update

graphql:
  servlet:
    mapping: /graphql

xmeta:
  security:
    jwt:
      # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
      base64-secret: ZTMxMDliNmRiMzU2ZDRjODlkMzZhOWQ2MDVlNzZjNmJkZmZkZTVjOThlNjMyYmUxNDA0NjBiZjVmNzMxOTNlYTg5MTNkMDNjMmRiOGIyMjkzZmFkMzM3ZTU2ZjU1YzM0YWIyMzQ4NWE5ZTUwMzdiMDdkNTgyYTRkMzAyNDYxZDU=
      # Token is valid 24 hours
      token-validity-in-seconds: 86400
      token-validity-in-seconds-for-remember-me: 2592000
  upload:
    minio:
      endpoint: 'http://localhost:9000'
      access-key: minio
      secret-key: minio123xmt1EIKgjcbfld6XHie
